POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkplZmYiLCJpZCI6IjYxYzA4YjljZTA0ZjI1MjE0NDBhZTRiOSIsImlhdCI6MTY0MDc5NzU0Mn0.WMa6In1pIDiPKOKHyq-ljWCqODO3WNzQxQOTJlpTBbE

{
	"title": "Bearer Token",
	"author": "Authorized",
	"url": "NONE",
	"likes": 1111
}